### PR TITLE
Quality of Life updates to initial build

### PR DESCRIPTION
**Pull request by KaiLumberNew**

### CODE REVIEW

**Review by Ali2DEFRA — CHANGES_REQUESTED** [review]
Requested Changes:
1 - account variable missing
2 - outlook closure - check with karen/BA
3 - single run multi json object doesn't seem to be referenced
4 - template copied not suitable  - need to configure it or use different template
e.g. json object used to control single/multi flow not referenced in state machine
5 - need to use updated library packages for reusable components

**Review by Ali2DEFRA — CHANGES_REQUESTED** [review]
optional changes
1 - use up to dat components to read config file and sharepoint config file
2 - remove empty invokes/unused variables and arguments
3 - some parts of the code could be simplified e.g. get data, using ienAttachments instead of str multiattach, adding TEST string to the config file

changed requested
1 -   "Robot/Username eq  '" & environment.UserDomainName & "' AND ReleaseName eq 'Demo Robot'"
this code will always evaluate false because the the release anme is not Demo Robot and username is missing the username and \\.
2 - remove or check if outlook already open to prevent executing code when not required
3- filepath for log file need to be fixed. currently appends the username creating a filepath that doesnt exist
reccomended use of string.format("C:\Users\{0}\Downloads\Uti...",username, ... )
4 - need to configure code to be pointed to live. Live config file needs to be in there
5 - get data email exception sallow possibility - need to differentiate between no data and error getting data
6 - account not filled in get data activity
7 - process transaction exit lines need to be re-ordered

**Review by Ali2DEFRA — CHANGES_REQUESTED** [review]
Optional

initialise state - exception leads to final state without doing anything - if there is an error at initialisation it will end successfully
making error identification difficult
reccomendation - delete parent try catch and exit transition line system exception leading out of intiialisation
same issue with process exception path - end in success. will indicate incorrect outcome in jobs on orchestrator for analysis

delete/move test logs/screen shots to sharepoint

remove xamls no longer in use - e.g. kill processes

use of excSystemException.Data("notes").ToString
the .data comes form global exception handler which is not being used here

log files and test data stored in

unused checkpoint exception path


Required changes

live config still missing - shared mail box email is required

duplicate variable found strNotes

BRE exception logging/reporting missing

in_dictConfig("Email Subject").ToString+in_mailTransactionItem.Body used in body

attachments no longer being deleted - use forward email to simplify further

get data - unhandled error + missing distinction between no emails and error getting emails

**Review by JasonSavory — APPROVED** [review]
Reviewed on call, all required changes done

**Pull request merged**
